// Drizzle schema — Postgres dialect (PGlite today, real Postgres later).
//
// Model: the live entity tables ARE the source of truth (CRUD); every row
// archives via `archived_at` (nothing is ever deleted). Alongside them, an
// append-only `actions` log
// records every mutation as one row carrying the field-level diff (before→after)
// of the entity it changed — so filtering by entity_id replays that entity's
// full history, and reading the stream is the activity feed.
//
// Migrations are generated by `bun run db:generate` into ./drizzle and applied
// at boot; don't hand-edit tables without regenerating.

import { bigint, index, integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";

// Domain enums — the single source of truth. Applied to columns via `.$type<>()`
// (no DB migration; `$inferSelect` yields these literal unions, and shared/types.ts
// derives the board-state types from them). Switch a column to `pgEnum` later if
// you want DB-level enforcement too.
export type TaskStatus =
  | "planned"
  | "launched"
  | "working"
  | "waiting_for_me"
  | "needs_review"
  | "github_action"
  | "done"
  | "abandoned"
  | "blocked"
  | "failed";
export type TaskKind = "planning" | "implementation" | "review" | "investigation";
export type GoalStatus = "active" | "done" | "abandoned";
export type MilestoneStatus = "pending" | "active" | "awaiting_approval" | "done" | "abandoned";
export type PlanStatus = "proposed" | "approved" | "rejected" | "promoted";
export type WorkstreamStatus = "active" | "waiting_for_me" | "done" | "abandoned";
export type SessionStatus = "starting" | "working" | "waiting" | "stale" | "closed";
export type ArtifactKind =
  | "pull_request"
  | "plan_proposal"
  | "task_proposal"
  | "investigation_report"
  | "question"
  | "review_request"
  | "human_execution_request";
export type Actor = "operator" | "supervisor" | "worker" | "github" | "dispatcher" | "system";

// The entity kinds an action can be logged against (the `entityType` column).
export type EntityType =
  | "workspace"
  | "goal"
  | "plan"
  | "workstream"
  | "milestone"
  | "task"
  | "session"
  | "artifact"
  | "claim"
  | "scratchpad";

// Every action verb written to the append-only log. Typed so a typo at any of
// the ~30 call sites is a compile error, and startsWith("operator_") filters
// stay honest.
export type ActionName =
  | "workspace_created"
  | "workspace_updated"
  | "goal_created"
  | "workstream_created"
  | "task_created"
  | "session_started"
  | "session_attached"
  | "milestone_created"
  | "milestone_updated"
  | "milestone_started"
  | "milestone_approved"
  | "milestone_archived"
  | "plan_proposed"
  | "plan_approved"
  | "plan_rejected"
  | "task_launched"
  | "task_resumed"
  | "worker_failed"
  | "claim_registered"
  | "worker_progressed"
  | "worker_asked_question"
  | "worker_requested_review"
  | "worker_marked_blocked"
  | "artifact_attached"
  | "operator_answered"
  | "operator_commented"
  | "operator_approved_review"
  | "operator_marked_task_done"
  | "operator_abandoned_task"
  | "scratchpad_edited"
  // archive / restore (nothing is ever deleted)
  | "workspace_archived"
  | "workspace_restored"
  | "goal_archived"
  | "goal_restored"
  | "task_archived"
  | "task_restored"
  | "milestone_restored";

// Common columns on every live entity table.
const lifecycle = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  archivedAt: timestamp("archived_at", { withTimezone: true }), // null = live (nothing is ever deleted)
};

export const workspaces = pgTable("workspaces", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  repoPath: text("repo_path"),
  subpath: text("subpath"),
  secrets: jsonb("secrets").$type<Record<string, string>>(),
  envFiles: jsonb("env_files").$type<string[]>(),
  setup: text("setup"),
  ...lifecycle,
});

export const goals = pgTable(
  "goals",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id").notNull(),
    title: text("title").notNull(),
    intent: text("intent"),
    status: text("status").$type<GoalStatus>().notNull().default("active"),
    ...lifecycle,
  },
  (t) => [index("idx_goals_workspace").on(t.workspaceId)],
);

export const milestones = pgTable(
  "milestones",
  {
    id: text("id").primaryKey(),
    goalId: text("goal_id").notNull(),
    title: text("title").notNull(),
    detail: text("detail"),
    orderHint: integer("order_hint").notNull().default(0),
    status: text("status").$type<MilestoneStatus>().notNull().default("pending"),
    ...lifecycle,
  },
  (t) => [index("idx_milestones_goal").on(t.goalId)],
);

export const plans = pgTable(
  "plans",
  {
    id: text("id").primaryKey(),
    goalId: text("goal_id").notNull(),
    title: text("title").notNull(),
    summary: text("summary"),
    status: text("status").$type<PlanStatus>().notNull().default("proposed"),
    proposedTasks:
      jsonb("proposed_tasks").$type<{ title: string; objective: string; kind: TaskKind }[]>(),
    ...lifecycle,
  },
  (t) => [index("idx_plans_goal").on(t.goalId)],
);

export const workstreams = pgTable(
  "workstreams",
  {
    id: text("id").primaryKey(),
    goalId: text("goal_id").notNull(),
    startingPlanId: text("starting_plan_id"),
    title: text("title").notNull(),
    status: text("status").$type<WorkstreamStatus>().notNull().default("active"),
    ...lifecycle,
  },
  (t) => [index("idx_workstreams_goal").on(t.goalId)],
);

export const tasks = pgTable(
  "tasks",
  {
    id: text("id").primaryKey(),
    workstreamId: text("workstream_id"),
    milestoneId: text("milestone_id"),
    planId: text("plan_id"),
    title: text("title").notNull(),
    objective: text("objective").notNull().default(""),
    kind: text("kind").$type<TaskKind>().notNull().default("implementation"),
    status: text("status").$type<TaskStatus>().notNull().default("planned"),
    sessionId: text("session_id"),
    branch: text("branch"),
    worktreePath: text("worktree_path"),
    baseRef: text("base_ref"),
    token: text("token"), // worker API token (durable binding for /api/w/:token)
    question: text("question"),
    lastProgress: text("last_progress"),
    orderHint: integer("order_hint"),
    afterTaskIds: jsonb("after_task_ids").$type<string[]>(),
    ...lifecycle,
  },
  (t) => [index("idx_tasks_workstream").on(t.workstreamId), index("idx_tasks_status").on(t.status)],
);

export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  workstreamId: text("workstream_id"),
  currentTaskId: text("current_task_id"),
  taskIds: jsonb("task_ids").$type<string[]>().notNull().default([]),
  status: text("status").$type<SessionStatus>().notNull().default("starting"),
  ...lifecycle,
});

export const artifacts = pgTable(
  "artifacts",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id").notNull(),
    sessionId: text("session_id"),
    kind: text("kind").$type<ArtifactKind>().notNull(),
    summary: text("summary"),
    payload: jsonb("payload").$type<Record<string, unknown>>(),
    ...lifecycle,
  },
  (t) => [index("idx_artifacts_task").on(t.taskId)],
);

export const claims = pgTable(
  "claims",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id").notNull(),
    sessionId: text("session_id"),
    summary: text("summary"),
    ...lifecycle,
  },
  (t) => [index("idx_claims_task").on(t.taskId)],
);

// Append-only audit: one row per mutation, carrying the entity's field-level
// diff. Never soft-deleted — this is the permanent history of actions.
export const actions = pgTable(
  "actions",
  {
    id: text("id").primaryKey(),
    seq: bigint("seq", { mode: "number" }).notNull(), // monotonic order
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    actor: text("actor").notNull(), // free-form: operator | worker | dispatcher | …
    action: text("action").notNull(), // e.g. task_status_changed, plan_approved
    entityType: text("entity_type").notNull(), // workspace | goal | plan | ... | task
    entityId: text("entity_id").notNull(),
    summary: text("summary"),
    // { field: { from, to }, ... } — the before→after delta for entityId.
    diff: jsonb("diff").$type<Record<string, { from: unknown; to: unknown }>>().notNull(),
  },
  (t) => [
    index("idx_actions_seq").on(t.seq),
    index("idx_actions_entity").on(t.entityType, t.entityId),
  ],
);

// ---- Scratchpad ----
// A single global catchall for the operator's loose notes; the supervisor reads
// it and can propose edits. One row, id = "main".
export const scratchpad = pgTable("scratchpad", {
  id: text("id").primaryKey(),
  content: text("content").notNull().default(""),
  ...lifecycle,
});

// ---- Chat (the Claude-style assistant surface) ----
// One row per conversation thread shown in the sidebar "Recents". `claudeSessionId`
// is claude's own session id, kept so each thread resumes via `claude -p --resume`.
export const chatThreads = pgTable("chat_threads", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id"),
  kind: text("kind").$type<"assistant" | "supervisor" | "worker">().notNull().default("assistant"),
  goalId: text("goal_id"),
  taskId: text("task_id"),
  title: text("title"), // null until auto-titled from the first message
  claudeSessionId: text("claude_session_id"),
  ...lifecycle,
});

// One row per message. `message` stores the serialized assistant-ui message
// (format-agnostic) so the history adapter can round-trip it verbatim; `seq`
// orders within a thread.
export const chatMessages = pgTable(
  "chat_messages",
  {
    id: text("id").primaryKey(),
    threadId: text("thread_id").notNull(),
    seq: bigint("seq", { mode: "number" }).notNull(),
    message: jsonb("message").$type<unknown>().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("idx_chat_messages_thread").on(t.threadId)],
);
